export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
} from './dialog';
export type {
  DialogCloseElement,
  DialogCloseProps,
  DialogContentElement,
  DialogContentProps,
  DialogDescriptionElement,
  DialogDescriptionProps,
  DialogFooterElement,
  DialogFooterProps,
  DialogHeaderElement,
  DialogHeaderProps,
  DialogOverlayElement,
  DialogOverlayProps,
  DialogPortalProps,
  DialogProps,
  DialogTitleElement,
  DialogTitleProps,
  DialogTriggerElement,
  DialogTriggerProps,
} from './types';
